region            = "us-east-1"
instance_type     = "t2.micro"
env               = "dev"
ami               = "ami-0ec10929233384c7f"
key_name          = "ansible-demo"
allowed_ssh_cidr  = "0.0.0.0/0"
bucket_name       = "krishna-dev-bucket-123"
