name: Terraform Drift Detection

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false

     - name: Terraform Plan (Drift Detection)
       id: plan
       run: |
         terraform plan | tee plan.txt
         if grep -q "No changes" plan.txt; then
           echo "drift=false" >> $GITHUB_OUTPUT
         else
           echo "drift=true" >> $GITHUB_OUTPUT
         fi

     - name: Slack Alert
       if: steps.plan.outputs.drift == 'true'
       run: |
         curl -X POST -H 'Content-type: application/json' \
         --data '{"text":" Terraform Drift Detected!"}' \
         ${{ secrets.SLACK_WEBHOOK_URL }}
