name: Terraform Drift Detection

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Day-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -input=false

      #  CAPTURE DRIFT + SAVE OUTPUT
      - name: Terraform Plan (Drift Detection)
        id: plan
        run: |
          set +e
          terraform plan -detailed-exitcode -no-color > plan.txt
          EXIT_CODE=$?

          echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT

          if [ $EXIT_CODE -eq 2 ]; then
            echo "drift=true" >> $GITHUB_OUTPUT
          else
            echo "drift=false" >> $GITHUB_OUTPUT
          fi

          exit 0

      #  DRIFT ALERT (WITH DETAILS + LINK)
      - name: Slack Alert (Drift Detected)
        if: steps.plan.outputs.drift == 'true'
        run: |
          MESSAGE=" *Terraform Drift Detected!*
Repo: $GITHUB_REPOSITORY
Branch: $GITHUB_REF_NAME
Run: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

Details:
$(head -n 20 plan.txt)"

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      #  SUCCESS MESSAGE (NO DRIFT)
      - name: Slack Alert (No Drift)
        if: steps.plan.outputs.drift == 'false'
        run: |
          MESSAGE=" No Terraform drift detected.
Repo: $GITHUB_REPOSITORY
Branch: $GITHUB_REF_NAME"

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
